// <auto-generated />
namespace SdmoPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LogEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201703170333267_LogEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
